name: Deploy to Alibaba Cloud SAE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '8' # Use your Java version
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package

      - name: Install Alibaba Cloud CLI
        run: pip install aliyuncli

      - name: Configure Alibaba Cloud credentials
        env:
          ALICLOUD_ACCESS_KEY_ID: ${{ secrets.ALICLOUD_ACCESS_KEY_ID }}
          ALICLOUD_ACCESS_KEY_SECRET: ${{ secrets.ALICLOUD_ACCESS_KEY_SECRET }}
        run: |
          aliyuncli configure set --profile aliyun --region <your-region> --access-key-id $ALICLOUD_ACCESS_KEY_ID --access-key-secret $ALICLOUD_ACCESS_KEY_SECRET

      - name: Upload WAR to OSS
        env:
          OSS_BUCKET_NAME: jasontest2025
        run: |
          aliyuncli oss cp target/your-java-backend.war oss://${OSS_BUCKET_NAME}/your-java-backend.war

